version: 0.2

env:
  parameter-store:
    CLOUDTRAIN_CODEBUILD_GIT_TAG_USER: "CLOUDTRAIN_CODEBUILD_GIT_TAG_USER"
    CLOUDTRAIN_CODEBUILD_GIT_TAG_EMAIL: "CLOUDTRAIN_CODEBUILD_GIT_TAG_EMAIL"
  secrets-manager:
    HARBOR_USER: "cloudtrain-codebuild-harbor:user"
    HARBOR_PASSWORD: "cloudtrain-codebuild-harbor:token"
    DOCKERHUB_USER: "cloudtrain-codebuild-dockerhub:docker-user"
    DOCKERHUB_PAT: "cloudtrain-codebuild-dockerhub:docker-pat"
    GITHUB_TOKEN: "cloudtrain-codebuild-github:msgoat_pat"

phases:
  install:
    on-failure: ABORT
    commands:
      - echo "Running phase install"
      - echo "Download and run common installation script"
      - aws s3 cp s3://s3-eu-west-1-cloudtrain-codebuild-shared/cloudtrain-codebuild-install.sh ~/
      - chmod u+x ~/cloudtrain-codebuild-install.sh
      - ~/cloudtrain-codebuild-install.sh
  pre_build:
    on-failure: ABORT
    commands:
      - echo "Running phase pre_build"
      - echo "Download common configuration files"
      - aws s3 cp s3://s3-eu-west-1-cloudtrain-codebuild-shared/.mvn/settings.xml /root/.m2/settings.xml
      - echo "Authenticate on DockerHub"
      - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PAT
      - echo "Authenticate on AWS ECR"
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 928593304691.dkr.ecr.eu-west-1.amazonaws.com
  build:
    on-failure: ABORT
    commands:
      - echo "Running phase build"
      - export GIT_BRANCH=${CODEBUILD_WEBHOOK_HEAD_REF:11}
      - export VERSION_REVISION=$(grep -m 1 '<revision>' pom.xml | cut -d '<' -f2  | cut -d '>' -f2)
      - export VERSION_CHANGELIST=${GIT_BRANCH:-main}
      - export VERSION_SHA1=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:8}
      - export PROJECT_VERSION=$VERSION_REVISION.$VERSION_CHANGELIST.$VERSION_SHA1
      - echo "Running commit-stage of the build using branch [$VERSION_CHANGELIST] and short commit hash [$VERSION_SHA1]"
      - mvn clean install -f pom.xml -B -ff -e -V -U -Dchangelist=.$VERSION_CHANGELIST -Dsha1=.$VERSION_SHA1
      - echo "Tag branch [$VERSION_CHANGELIST] with git tag [$PROJECT_VERSION] on behalf of CodeBuild initiator [$CODEBUILD_INITIATOR] and GitHub actor [$CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID]"
      - git config user.name "$CLOUDTRAIN_CODEBUILD_GIT_TAG_USER"
      - git config user.email "$CLOUDTRAIN_CODEBUILD_GIT_TAG_EMAIL"
      - git tag -a $PROJECT_VERSION -m "$CODEBUILD_BUILD_ARN"
      - git remote set-url origin "https://$GITHUB_TOKEN@github.com/msgoat/codebuild-cbe-k8s.git"
      - git push origin HEAD:$VERSION_CHANGELIST $PROJECT_VERSION
  post_build:
    commands:
      - echo "Running phase post_build"

cache:
  paths:
    - "/root/.m2/**/*"